//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alloment_system.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppS_info
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Telefone { get; set; }
        public string Department { get; set; }
    }
}
