//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alloment_system.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories1
    {
        public int P_id { get; set; }
        public string CategoryName { get; set; }
        public string P_name { get; set; }
        public string P_price { get; set; }
    }
}
