//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alloment_system.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public Nullable<int> DepartmentId { get; set; }
        public string EmpName { get; set; }
        public string DepartmentName { get; set; }
        public int EmpId { get; set; }
        public Nullable<int> OfficeNumber { get; set; }
    }
}
