//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alloment_system.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedHolders
    {
        public int SHid { get; set; }
        public string SHname { get; set; }
        public int SHage { get; set; }
        public string SharedAmount { get; set; }
    }
}
